global:
  scrape_interval: 10s
  evaluation_interval: 10s
  # Attach these labels to all time series scraped by this Prometheus instance
  external_labels:
    environment: 'local'
    project: 'apex-recommendation-engine'

rule_files:
  - "prometheus.rules.yml"

scrape_configs:
  - job_name: 'nova-backend'
    static_configs:
      - targets: ['nova-backend:8000']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-feature-store:6379']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-db:5432']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
