[pytest]
filterwarnings =
    ignore:builtin type SwigPyPacked has no __module__ attribute:DeprecationWarning
    ignore:builtin type SwigPyObject has no __module__ attribute:DeprecationWarning
    ignore:builtin type swigvarlink has no __module__ attribute:DeprecationWarning
    ignore:'asyncio\.iscoroutinefunction' is deprecated and slated for removal in Python 3\.16.*:DeprecationWarning:slowapi\.extension
