name = "movie-recommendation-system"
main = "cloudflare_worker/index.ts"
compatibility_date = "2026-08-01"

[ai]
binding = "AI"

[[r2_buckets]]
binding = "DATASET_BUCKET"
bucket_name = "movie-rec-dataset"
