name = "movie-recommendation-system"
main = "cloudflare_worker/index.ts"
compatibility_date = "2026-08-01"

[ai]
binding = "AI"

[[kv_namespaces]]
binding = "RECOMMENDATION_CACHE"
id = "59a3a81abdee46b08691c55412a3236b"

# Enable R2 bucket in Cloudflare dashboard to activate R2 binding:
# [[r2_buckets]]
# binding = "DATASET_BUCKET"
# bucket_name = "movie-rec-dataset"
