"""
Shared pipeline dataclasses for the APEX Movie Recommendation System.

This module defines the data types that flow between the three pipeline stages:
  - CandidateItem  (output of RetrievalPipeline)
  - RankedItem     (output of RankingPipeline)
  - FinalItem      (output of RerankingPipeline)

Circular-import constraint
--------------------------
This module MUST have ZERO imports from other ``backend/`` modules.
All three pipeline modules (retrieval_pipeline, ranking_pipeline,
reranking_pipeline) import their input/output types from here, so any
back-import would create a circular dependency.  The only allowed imports
are from the Python standard library and ``typing``.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass
class CandidateItem:
    """
    A single candidate produced by the retrieval stage (Stage 1).

    Attributes
    ----------
    movie_id:
        Unique identifier for the movie in the catalog.
    retrieval_score:
        Raw relevance score assigned by the retrieval source.
        Higher is more relevant.
    retrieval_source:
        Which retrieval mechanism produced this candidate.
        One of ``"faiss"``, ``"tfidf"``, ``"knowledge_graph"``, or
        ``"hybrid"`` (when scores from multiple sources are merged).
    metadata:
        Arbitrary key/value pairs forwarded from the retrieval source
        (e.g. title, genre, year).  Defaults to an empty dict.
    """

    movie_id: int
    retrieval_score: float
    retrieval_source: Literal["faiss", "tfidf", "knowledge_graph", "hybrid"]
    metadata: dict = field(default_factory=dict)


@dataclass
class RankedItem:
    """
    A candidate that has been scored and ordered by the ranking stage (Stage 2).

    Contains all fields from ``CandidateItem`` plus ranking-specific signals.

    Attributes
    ----------
    movie_id:
        Unique identifier for the movie in the catalog.
    retrieval_score:
        Raw relevance score from the retrieval stage.
    retrieval_source:
        Which retrieval mechanism produced this candidate.
    ensemble_score:
        Score produced by the neural ensemble (LightGCN / Quantum / SASRec).
        May equal ``retrieval_score`` when ``use_neural_ensemble=False``.
    ranker_score:
        Score produced by the learned ranker (MMoE / LightGBM).
        May equal ``ensemble_score`` when ``use_learned_ranker=False``.
    final_rank:
        1-indexed position after blending and sorting (1 = best).
    retrieval_signals:
        Per-source score breakdown used for explainability and debugging.
        Defaults to an empty dict.
    metadata:
        Arbitrary key/value pairs forwarded from the retrieval stage.
        Defaults to an empty dict.
    """

    movie_id: int
    retrieval_score: float
    retrieval_source: str
    ensemble_score: float
    ranker_score: float
    final_rank: int
    retrieval_signals: dict = field(default_factory=dict)
    metadata: dict = field(default_factory=dict)


@dataclass
class FinalItem:
    """
    A ranked candidate that has passed through the reranking stage (Stage 3).

    Contains all fields from ``RankedItem`` plus diversity, safety, and
    explanation signals added by the reranking stage.

    Attributes
    ----------
    movie_id:
        Unique identifier for the movie in the catalog.
    retrieval_score:
        Raw relevance score from the retrieval stage.
    retrieval_source:
        Which retrieval mechanism produced this candidate.
    ensemble_score:
        Score produced by the neural ensemble.
    ranker_score:
        Score produced by the learned ranker.
    final_rank:
        1-indexed position after blending and sorting (1 = best).
    diversity_score:
        MMR diversity contribution for this item (higher = more diverse
        relative to already-selected items).
    safety_passed:
        ``True`` if the RL safety filter did not suppress this item.
    explanation:
        Optional natural-language explanation generated by the LLM
        reranking step.  ``None`` when LLM reranking is disabled.
    retrieval_signals:
        Per-source score breakdown used for explainability and debugging.
        Defaults to an empty dict.
    metadata:
        Arbitrary key/value pairs forwarded from earlier pipeline stages.
        Defaults to an empty dict.
    """

    movie_id: int
    retrieval_score: float
    retrieval_source: str
    ensemble_score: float
    ranker_score: float
    final_rank: int
    diversity_score: float
    safety_passed: bool
    explanation: str | None
    retrieval_signals: dict = field(default_factory=dict)
    metadata: dict = field(default_factory=dict)
