# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from backend.proto import recommendation_pb2 as backend_dot_proto_dot_recommendation__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in backend/proto/recommendation_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RecommendationServiceStub:
    """Service definition for APEX High-Throughput Recommendation Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetRecommendations = channel.unary_unary(
                '/apex.recommendation.v1.RecommendationService/GetRecommendations',
                request_serializer=backend_dot_proto_dot_recommendation__pb2.RecommendationRequest.SerializeToString,
                response_deserializer=backend_dot_proto_dot_recommendation__pb2.RecommendationResponse.FromString,
                _registered_method=True)
        self.SearchCatalog = channel.unary_unary(
                '/apex.recommendation.v1.RecommendationService/SearchCatalog',
                request_serializer=backend_dot_proto_dot_recommendation__pb2.SearchRequest.SerializeToString,
                response_deserializer=backend_dot_proto_dot_recommendation__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.stream_unary(
                '/apex.recommendation.v1.RecommendationService/StreamEvents',
                request_serializer=backend_dot_proto_dot_recommendation__pb2.EventRequest.SerializeToString,
                response_deserializer=backend_dot_proto_dot_recommendation__pb2.EventResponse.FromString,
                _registered_method=True)


class RecommendationServiceServicer:
    """Service definition for APEX High-Throughput Recommendation Service
    """

    def GetRecommendations(self, request, context):
        """Retrieve ranked recommendations for a movie ID or user session
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SearchCatalog(self, request, context):
        """Search catalog items via vector embeddings / semantic query
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request_iterator, context):
        """Stream real-time behavior telemetry events
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecommendationServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetRecommendations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRecommendations,
                    request_deserializer=backend_dot_proto_dot_recommendation__pb2.RecommendationRequest.FromString,
                    response_serializer=backend_dot_proto_dot_recommendation__pb2.RecommendationResponse.SerializeToString,
            ),
            'SearchCatalog': grpc.unary_unary_rpc_method_handler(
                    servicer.SearchCatalog,
                    request_deserializer=backend_dot_proto_dot_recommendation__pb2.SearchRequest.FromString,
                    response_serializer=backend_dot_proto_dot_recommendation__pb2.SearchResponse.SerializeToString,
            ),
            'StreamEvents': grpc.stream_unary_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=backend_dot_proto_dot_recommendation__pb2.EventRequest.FromString,
                    response_serializer=backend_dot_proto_dot_recommendation__pb2.EventResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'apex.recommendation.v1.RecommendationService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('apex.recommendation.v1.RecommendationService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RecommendationService:
    """Service definition for APEX High-Throughput Recommendation Service
    """

    @staticmethod
    def GetRecommendations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apex.recommendation.v1.RecommendationService/GetRecommendations',
            backend_dot_proto_dot_recommendation__pb2.RecommendationRequest.SerializeToString,
            backend_dot_proto_dot_recommendation__pb2.RecommendationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SearchCatalog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/apex.recommendation.v1.RecommendationService/SearchCatalog',
            backend_dot_proto_dot_recommendation__pb2.SearchRequest.SerializeToString,
            backend_dot_proto_dot_recommendation__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/apex.recommendation.v1.RecommendationService/StreamEvents',
            backend_dot_proto_dot_recommendation__pb2.EventRequest.SerializeToString,
            backend_dot_proto_dot_recommendation__pb2.EventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
